name: Qodana
on:
  workflow_dispatch:
  
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch
      - 'releases/*' # The release branches
      - '*' # The all branches

jobs:
  qodana:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          args: |
            -l, qodana-jvm
