name: Code coverage fresh code

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run tests
        run: |
          ./gradlew test 
          ./gradlew jacocoTestReport

      - name: Archive coverage data
        uses: actions/upload-artifact@v2
        with:
          name: build/reports/jacoco/test
          path: .qodana/code-coverage

      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_CODE_COVERAGE }}
        with:
          pr-mode: true # Enable the pull-request mode
