name: Code coverage fresh code

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run tests
        run: |
          ./gradlew test 
          ./gradlew jacocoTestReport

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: jacocoCodeCoverage
          path: .qodana/code-coverage
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}
          
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.2.6
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_FRESH_COVERAGE }}
        with:
          pr-mode: true # Enable the pull-request mode
          args: |
            -l,${{ secrets.SPACE_REGISTRY }}/p/sa/containers/qodana-jvm:2024.3-rc

